version: '3.9'
services:
  node-api:
    image: armandosalazar/node-api:1.0
    build: .
    container_name: node-api
    ports:
      - 80:3000
    environment:
      - NODE_ENV=development
    command: npm run dev
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
