version: '3.9'
services:
  node-api:
    build: .
    container_name: node-api
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
